//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.*;

public class New_CustomerGUI implements ActionListener {
    private JDialog dialog;
    private JPanel pa;
    private JLabel lb1;
    private JLabel lb2;
    private JLabel lb3;
    private JLabel lb4;
    private JLabel lb5;
    private JLabel jcomp7;
    private JLabel lb6;
    private JTextField te1;
    private JTextField te2;
    private JTextField te3;
    private JTextField te4;
    private JTextField te5;
    private JTextField te6;
    private JButton bu;

    public New_CustomerGUI(JFrame parentFrame) {
    
        dialog = new JDialog(parentFrame, "New Customer", true);  
        pa = new JPanel();
        lb1 = new JLabel ("NEW");
        lb2 = new JLabel ("Name :");
        lb3 = new JLabel ("Phone : ");
        lb4 = new JLabel ("Address :");
        lb5 = new JLabel ("E-mail :");
        jcomp7 = new JLabel ("FB :");
        lb6 = new JLabel ("Line : ");
        te1 = new JTextField ();
        te2 = new JTextField ();
        te3 = new JTextField ();
        te4 = new JTextField ();
        te5 = new JTextField ();
        te6 = new JTextField ();
        bu = new JButton ("NEXT");

        pa.setPreferredSize (new Dimension (350, 300));
        pa.setLayout (null);
        
        bu.addActionListener(this);

        pa.add (lb1);
        pa.add (lb2);
        pa.add (lb3);
        pa.add (lb4);
        pa.add (lb5);
        pa.add (jcomp7);
        pa.add (lb6);
        pa.add (te1);
        pa.add (te2);
        pa.add (te3);
        pa.add (te4);
        pa.add (te5);
        pa.add (te6);
        pa.add (bu);
        dialog.add(pa);
        
        lb1.setBounds (130, 5, 100, 25);
        lb2.setBounds (5, 45, 100, 25);
        lb3.setBounds (5, 70, 100, 25);
        lb4.setBounds (5, 95, 100, 25);
        lb5.setBounds (5, 125, 100, 25);
        jcomp7.setBounds (5, 155, 100, 25);
        lb6.setBounds (5, 180, 100, 25);
        te1.setBounds (80, 50, 240, 20);
        te2.setBounds (80, 75, 240, 20);
        te3.setBounds (80, 100, 240, 20);
        te4.setBounds (80, 130, 240, 20);
        te5.setBounds (80, 155, 240, 20);
        te6.setBounds (80, 180, 240, 20);
        bu.setBounds (260, 265, 75, 25);
        
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setVisible (true);
    }


    

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(bu)){
            new AddMoneyGUI(dialog);
        }
    }
}
